from __future__ import annotations

import json
import math
import struct
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np

from .config import ToolConfig
from .features import FEATURE_ORDER


def _json_default(value: Any) -> Any:
    if isinstance(value, (np.integer,)): return int(value)
    if isinstance(value, (np.floating,)): return float(value)
    if isinstance(value, np.ndarray): return value.tolist()
    raise TypeError(f"Cannot serialize {type(value).__name__}")


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True, default=_json_default, allow_nan=False) + "\n", encoding="utf-8")


def read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def canonicalize_predictor(artifact: dict[str, Any], controller: dict[str, Any] | None = None, created_at: str | None = None) -> dict[str, Any]:
    result = dict(artifact)
    result["created_at_utc"] = created_at or datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    if controller is not None:
        result["controller"] = controller
    return result


def _fnv_u32(checksum: int, value: int) -> int:
    for shift in range(0, 32, 8):
        checksum ^= (value >> shift) & 0xFF
        checksum = (checksum * 16777619) & 0xFFFFFFFF
    return checksum


def _fnv_float(checksum: int, value: float) -> int:
    bits = struct.unpack("<I", struct.pack("<f", np.float32(value)))[0]
    return _fnv_u32(checksum, bits)


def firmware_checksum(model: dict[str, Any], config: ToolConfig) -> int:
    controller = model["controller"]
    checksum = 2166136261
    for value in (model["model_version"], model["feature_schema_version"], model["training_data_hash"]):
        checksum = _fnv_u32(checksum, int(value))
    for value in (
        config.features.filter_alpha, controller["prediction_deadband_c"], controller["prediction_gain_per_c"],
        controller["hard_cutoff_margin_c"], controller["activation_band_c"], config.features.maximum_absolute_slope_c_per_s,
        30.0, config.controller.recovery_stable_slope_c_per_s,
    ):
        checksum = _fnv_float(checksum, value)
    checksum = _fnv_u32(checksum, config.features.minimum_interval_ms)
    checksum = _fnv_u32(checksum, config.features.maximum_interval_ms)
    for kind in ("minimum", "maximum"):
        for feature in FEATURE_ORDER:
            checksum = _fnv_float(checksum, model["input_ranges"][feature][kind])
    for horizon in (5, 10, 20):
        horizon_model = model["models"][str(horizon)]
        checksum = _fnv_float(checksum, horizon_model["intercept"])
        for coefficient in horizon_model["coefficients"]:
            checksum = _fnv_float(checksum, coefficient)
    return checksum


def _float(value: float) -> str:
    value = float(np.float32(value))
    if not math.isfinite(value): raise ValueError("Firmware values must be finite.")
    rendered = f"{value:.9g}"
    if "." not in rendered and "e" not in rendered.lower():
        rendered += ".0"
    return rendered + "F"


def render_firmware_header(model: dict[str, Any], config: ToolConfig) -> str:
    if not model.get("promotion", {}).get("eligible", False):
        raise ValueError("Firmware header export is blocked because the candidate failed promotion.")
    checksum = firmware_checksum(model, config)
    controller = model["controller"]
    minimum = ", ".join(_float(model["input_ranges"][name]["minimum"]) for name in FEATURE_ORDER)
    maximum = ", ".join(_float(model["input_ranges"][name]["maximum"]) for name in FEATURE_ORDER)
    horizon_lines = []
    for horizon in (5, 10, 20):
        item = model["models"][str(horizon)]
        coefficients = ", ".join(_float(value) for value in item["coefficients"])
        horizon_lines.append(f"    {{{_float(item['intercept'])}, {{{{{coefficients}}}}}}}")
    rendered_horizons = ",\n".join(horizon_lines)
    metric_summary = ", ".join(
        f"{horizon}s MAE={model['models'][str(horizon)]['metrics']['mae']:.6g}C"
        for horizon in (5, 10, 20)
    )
    return f"""// Generated by philcoino-thermal. Manual review is required before firmware use.
// Created: {model.get('created_at_utc', 'unspecified')}
// Dataset SHA-256: {model['dataset_sha256']}
// Model/schema version: {model['model_version']}/{model['feature_schema_version']}
// Held-out validation: {metric_summary}
// Feature order: {', '.join(FEATURE_ORDER)}
#pragma once

#include "philcoino/prediction_config.hpp"

namespace philcoino::config {{

inline constexpr TemperaturePredictionConfig kGeneratedTemperaturePredictionConfig{{
    {int(model['model_version'])}U,
    {int(model['feature_schema_version'])}U,
    0x{int(model['training_data_hash']):08X}U,
    0x{checksum:08X}U,
    {_float(config.features.filter_alpha)},
    {_float(controller['prediction_deadband_c'])},
    {_float(controller['prediction_gain_per_c'])},
    {_float(controller['hard_cutoff_margin_c'])},
    {_float(controller['activation_band_c'])},
    {_float(config.features.maximum_absolute_slope_c_per_s)},
    30.0F,
    {_float(config.controller.recovery_stable_slope_c_per_s)},
    {config.features.minimum_interval_ms}U,
    {config.features.maximum_interval_ms}U,
    {{{{{minimum}}}, {{{maximum}}}}},
{rendered_horizons}
}};

}}  // namespace philcoino::config
"""


def export_firmware(model: dict[str, Any], output: Path, config: ToolConfig) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_firmware_header(model, config), encoding="utf-8")
    return output
